agent_config:
  _target_: sherpa_ai.config.task_config.AgentConfig
doc_search:
  _target_: actions.DocumentSearch
  embedding_function: ${embedding_func}
  html_filename: tender.html
  k: 4
  pdf_filename: RFT-24-317 Mowers-FINAL.pdf
embedding_func:
  _target_: langchain.embeddings.SentenceTransformerEmbeddings
  model_name: sentence-transformers/all-mpnet-base-v2
llm:
  _target_: langchain.chat_models.ChatOpenAI
  model_name: gpt-3.5-turbo
  temperature: 0
qa_agent:
  _target_: sherpa_ai.agents.qa_agent.QAAgent
  actions:
  - ${doc_search}
  agent_config: ${agent_config}
  description: You are a question answering assistant helping users to find answers
    to their questions. Based on the input question, you will provide the answer from
    the text ONLY.
  llm: ${llm}
  name: QA Sherpa
  num_runs: 1
  shared_memory: ${shared_memory}
shared_memory:
  _target_: sherpa_ai.memory.shared_memory.SharedMemory
  objective: Answer the question
